### ISSUE TITLE
CSRF Token Mismatch

### ISSUE THREAD

**Issue by Desoleh** [stanfortonski/Laravel-Blog#2]
**Describe the bug**
when i log in with user at seeder, i get an error "Page expired | 419, Probably your session expired.
in debugbar "CSRF Token Mismatch"
Likewise, after trying to register, the result is still an error

**To Reproduce**
1. Composer install
2. php artisan key:generate
3. php artisan migrate --seed
4. login at admin.localhost:8000/login
5. See error

**Expected behavior**

**Screenshots**
<img width="473" alt="Screenshot_2_login" src="https://user-images.githubusercontent.com/24294858/129435303-f9ecc2cc-7a93-444d-a403-7fb3d4081583.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome, firevox]
 - 
**.env setting**
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost
APP_DISQUS=
SESSION_DOMAIN=.localhost

**Comment by stanislawfortonski** [comment]
Hi! This is probably caused by wrong address. Laravel  "is waiting" for http://admin.localhost/login so http://admin.localhost:8000/login is wrong.  The most reliable will be the change server configuration. Just change port to 80.

**Comment by stanislawfortonski** [comment]
If that does not work check subdomain (admin.) configuration in the local server.

**Comment by Desoleh** [comment]
Thanks in advice.
This issue solved when I change localhost to laravel-blog.test (with valet installed).
Thanks....

**Comment by stanislawfortonski** [comment]
Nice to hear :)
