### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by jeevatrippy** [stanfortonski/Laravel-Blog#3]
Your question here...
Hi,
I install the application successfully, I have a doubt about APP_DISQUS  and SESSION_DOMAIN in .env file. can you please explain this?

And how can I access the admin dashboard in this project, I seen a file named web-admin in the routes folder.

Please help me with this.
Thank You

**Comment by stanislawfortonski** [comment]
Hi!

SESSION_DOMAIN allow us to share user state between subdomains.
APP_DISQUS this is the url to embed.js file. For example: https://yoursitename.disqus.com/embed.js. You have to create an new site on Disqus. Read here: https://help.disqus.com/en/articles/1717112-universal-embed-code
